remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-analytics

title: Joshua Long
email: jjlongts19@gmail.com
description: Senior Software Developer (Frontend)
google_analytics: G-NMY0F4WPST
url: "https://joshuagnol.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/image.jpeg



# Build settings

markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Joshua Gnol" 
