remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Joshua Long
email: jjlongts19@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  About me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshuagnol.github.io" # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: [true]
google_analytics: [Your Google Analytics tracking ID]

# Build settings

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Joshua Gnol" 